In [2]:
import numpy as np

# 1. Create a 3x3x3 array with random values

In [3]:
np.random.randn(3,3,3)

array([[[ 0.93096418, -0.190159  , -1.16892829],
        [ 1.76535588,  0.68487333,  0.40100982],
        [ 0.19516483,  0.45584245, -1.39735934]],

       [[-0.61058029, -1.23513267,  0.09950094],
        [ 0.16290213,  2.2377699 ,  0.82428584],
        [ 0.52359352, -0.88412877,  0.0695874 ]],

       [[ 0.92300127, -0.42515491, -0.20987164],
        [-0.87877911, -1.65385564, -0.27580227],
        [ 1.39788041, -0.6043122 ,  1.26135704]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
b= [1,2,3,4]
a = np.diag(b , k = -1) # k=-1 => Lower Diagonal,,,, k=1==>> Upper Diagonal
print (a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
a = np.zeros((8,8), dtype=int)
a[::2 , 1::2]=1
a[1::2 , ::2]=1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [6]:
a = np.random.randn(5,5)
max = a.max()
min =a.min()

a= (a-min)/(max-min)
a # All values normalized (betn 0 and 1)

array([[0.33383055, 0.42502606, 0.25355734, 0.21331766, 0.44025943],
       [1.        , 0.40325364, 0.22250742, 0.27414761, 0.30776548],
       [0.52628872, 0.74079687, 0.14821487, 0.67136057, 0.22156667],
       [0.35530953, 0.09431812, 0.54371314, 0.93448189, 0.34672488],
       [0.        , 0.18471097, 0.78292199, 0.57044513, 0.6105804 ]])

# 5. How to find common values between two arrays?

In [7]:
x = np.array([1,2,3,4,5,6])
y = np.array([4,5,6,7,8,9])

np.intersect1d(x,y)

array([4, 5, 6])

# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
from datetime import date,timedelta

today = date.today()
print("Today's Date is : ",today)

yesterday = today - timedelta(days = 1)
print("Yesterday's Date :",yesterday)

tommorow = today + timedelta(days = 1)
print("Tommorow's Date :",tommorow)

Today's Date is :  2020-07-28
Yesterday's Date : 2020-07-27
Tommorow's Date : 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [9]:
# Equal Arrays testing
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

comparison = a==b
print("Comparison")
print(comparison)

overall = comparison.all()
print("Overall:",overall)

# Not equal Arrays testing
a = np.array([1,2,3])
b = np.array([4,2,3])
print("\n")
comparison = a==b
print("Comparison")
print(comparison)  # Itcompares Position Wise

overall = comparison.all()
print("Overall:",overall)

Comparison
[[ True  True  True]
 [ True  True  True]]
Overall: True


Comparison
[False  True  True]
Overall: False


# 9. How to print all the values of an array?

In [14]:
vec = np.arange(10)
print(vec)

[0 1 2 3 4 5 6 7 8 9]


# 10.Subtract the mean of each row of a matrix

In [15]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

col = np.mean(a,axis=0) #Column
row = np.mean(a,axis=1) #Row
print("Col:",col)
print("row:",row)

#Subtracting Each rows Mean
sub=0
for i in row:
    sub = i-sub
    
print(sub)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Col: [4. 5. 6.]
row: [2. 5. 8.]
5.0


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [18]:
#Vector
v1 = np.array([1,2,3,4,5])

#Indices Vector
i = np.random.randint(0,len(v1),20)        # in the range of 0,5 generate 20 numbers 
print("Indices",i)
np.add.at(v1,i,1)                          # Add 1 at i indices in v1 vector

print("v1 after adding 1 at indices",v1) 

Indices [4 3 4 3 2 3 2 1 4 1 0 0 4 0 2 2 0 2 4 3]
v1 after adding 1 at indices [ 5  4  8  8 10]


# 12.How to get the diagonal of a dot product?

In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,20,30],[40,50,60],[70,80,90]])

dp = a.dot(b) #Dot Product
print("Dot Product\n",dp)

print("Diagonal of Dot Product\n",np.diag(dp))

Dot Product
 [[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]
Diagonal of Dot Product
 [ 300  810 1500]


# 13.How to find the most frequent value in an array?

In [20]:
a =list(np.random.randint(0,5,20)) # Random array of size 20 having values between 0 and 5
print("Array\n",a)
a_uniq = list(dict.fromkeys(a))
max_cnt = a.count(a_uniq[0])
max_i = 0

for i in range(1,len(a_uniq)):
    if a.count(a_uniq[i]) > max_cnt:
        max_cnt = a.count(a_uniq[i])
        max_i = i
        
print()
print("Max Freq :",max_cnt,"Of Value :",a_uniq[max_i])

Array
 [2, 1, 4, 4, 1, 1, 1, 0, 3, 0, 2, 3, 0, 1, 3, 1, 0, 2, 2, 1]

Max Freq : 7 Of Value : 1


# 15.How to create a record array from a regular array?

In [22]:
x = np.zeros((2,),dtype=('i4,f4,a10'))
x[:] = [(1,2.,'Hello'),(2,3.,"World")] # Record Array
x

array([(1, 2., b'Hello'), (2, 3., b'World')],
      dtype=[('f0', '<i4'), ('f1', '<f4'), ('f2', 'S10')])

In [23]:
print("First Record:",x[0])
print("Second Record:",x[1])

First Record: (1, 2., b'Hello')
Second Record: (2, 3., b'World')
